import Testing
import Foundation
import CryptoKit
@testable import AiTaskbarCore

@Suite("SecretBox — AES-GCM at-rest encryption")
struct SecretBoxTests {
    static let macA = "11111111-2222-3333-4444-555555555555"
    static let macB = "AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE"
    static let field = "zai.api_key"

    @Test("round-trip restores the original plaintext")
    func round_trip_restores_plaintext() throws {
        let pt = "sk-or-v1-abc-123-456-789"
        let enc = try SecretBox.encrypt(pt, field: Self.field)
        let back = try SecretBox.decryptIfPresent(enc, field: Self.field)
        #expect(back == pt)
    }

    @Test("with a machine id, encrypt writes enc:v2 and only that machine reads it")
    func v2_is_machine_bound() throws {
        let enc = try SecretBox.encrypt("sk-bound", field: Self.field, machineID: Self.macA)
        #expect(enc.hasPrefix(SecretBox.prefixV2))
        #expect(try SecretBox.decryptIfPresent(enc, field: Self.field, machineID: Self.macA) == "sk-bound")
        #expect(throws: AppError.self) {
            _ = try SecretBox.decryptIfPresent(enc, field: Self.field, machineID: Self.macB)
        }
        #expect(throws: AppError.self) {
            _ = try SecretBox.decryptIfPresent(enc, field: Self.field, machineID: nil)
        }
    }

    @Test("without a machine id, encrypt falls back to enc:v1, readable anywhere")
    func v1_fallback_without_machine_id() throws {
        let enc = try SecretBox.encrypt("sk-legacy", field: Self.field, machineID: nil)
        #expect(enc.hasPrefix(SecretBox.prefix))
        #expect(try SecretBox.decryptIfPresent(enc, field: Self.field, machineID: Self.macA) == "sk-legacy")
        #expect(try SecretBox.decryptIfPresent(enc, field: Self.field, machineID: nil) == "sk-legacy")
    }

    @Test("a v2 value moved to another field does not open there")
    func v2_is_field_bound() throws {
        let enc = try SecretBox.encrypt("sk-bound", field: "zai.api_key", machineID: Self.macA)
        #expect(try SecretBox.decryptIfPresent(enc, field: "zai.api_key", machineID: Self.macA) == "sk-bound")
        #expect(throws: AppError.self) {
            _ = try SecretBox.decryptIfPresent(enc, field: "openrouter.api_key", machineID: Self.macA)
        }
    }

    @Test("v1 has no field binding: legacy values open under any field")
    func v1_is_not_field_bound() throws {
        let enc = try SecretBox.encrypt("sk-legacy", field: "zai.api_key", machineID: nil)
        #expect(try SecretBox.decryptIfPresent(enc, field: "xai.api_key", machineID: nil) == "sk-legacy")
    }

    /// Frozen wire-format contract. Generated by an independent CryptoKit
    /// script (HKDF-SHA256: IKM = hardware UUID, salt
    /// "ai-taskbar.secretbox.v2", info "ai-taskbar.secretbox.v2/config-secret-key";
    /// AES-GCM nonce 00…0b, AAD "ai-taskbar.config-field:zai.api_key").
    /// If this fails, the v2 derivation or binding changed and every value
    /// already on users' disks would stop opening — that needs a v3 prefix,
    /// not an edit here.
    @Test("golden enc:v2 vector still opens (format is frozen)")
    func v2_golden_vector() throws {
        let golden = "enc:v2:AAECAwQFBgcICQoLo42oK3ImjuLKV94plTlr1wrGgFqTChQMsUD6YA=="
        #expect(try SecretBox.decryptIfPresent(golden, field: "zai.api_key", machineID: Self.macA) == "sk-golden-v2")
        #expect(throws: AppError.self) {
            _ = try SecretBox.decryptIfPresent(golden, field: "zai.api_key", machineID: Self.macB)
        }
    }

    @Test("isCurrentFormat: v2 is current with a machine id; any encryption without one")
    func is_current_format() {
        #expect(SecretBox.isCurrentFormat("enc:v2:AAA", machineID: Self.macA))
        #expect(!SecretBox.isCurrentFormat("enc:v1:AAA", machineID: Self.macA))
        #expect(!SecretBox.isCurrentFormat("plain", machineID: Self.macA))
        #expect(SecretBox.isCurrentFormat("enc:v1:AAA", machineID: nil))
        #expect(!SecretBox.isCurrentFormat("plain", machineID: nil))
    }

    @Test("the real hardware UUID is readable and stable on this Mac")
    func machine_identity_reads_uuid() throws {
        let id = try #require(MachineIdentity.current)
        #expect(id.count == 36)
        #expect(MachineIdentity.hardwareUUID() == id)
    }

    @Test("encrypt is non-deterministic — same plaintext yields different ciphertext")
    func encrypt_non_deterministic() throws {
        let pt = "sk-same-value"
        let a = try SecretBox.encrypt(pt, field: Self.field)
        let b = try SecretBox.encrypt(pt, field: Self.field)
        #expect(a != b, "AES-GCM with random nonce must produce different ciphertexts")
        // Both decrypt back to the same source, though.
        #expect(try SecretBox.decryptIfPresent(a, field: Self.field) == pt)
        #expect(try SecretBox.decryptIfPresent(b, field: Self.field) == pt)
    }

    @Test("decryptIfPresent returns nil for plaintext (non-prefixed) input — backward compat")
    func decrypt_returns_nil_for_plaintext() throws {
        #expect(try SecretBox.decryptIfPresent("sk-plaintext-no-prefix", field: Self.field) == nil)
        #expect(try SecretBox.decryptIfPresent("", field: Self.field) == nil)
    }

    @Test("isEncrypted identifies only enc:v1: / enc:v2: payloads")
    func is_encrypted_prefix_check() {
        #expect(SecretBox.isEncrypted("enc:v1:AAA"))
        #expect(SecretBox.isEncrypted("enc:v2:AAA"))
        #expect(!SecretBox.isEncrypted("enc:v3:AAA"))
        #expect(!SecretBox.isEncrypted("sk-plaintext"))
        #expect(!SecretBox.isEncrypted(""))
        #expect(!SecretBox.isEncrypted("ENC:V1:AAA"))  // case-sensitive
    }

    @Test("tampered ciphertext throws on decrypt (GCM auth tag catches it)")
    func tamper_throws() throws {
        let enc = try SecretBox.encrypt("secret", field: Self.field)
        // Flip a byte in the base64 payload — should fail GCM auth.
        var bytes = Array(enc.utf8)
        let prefixLen = SecretBox.prefix.count
        bytes[prefixLen + 2] = (bytes[prefixLen + 2] == 0x41 ? 0x42 : 0x41)  // 'A' <-> 'B'
        let tampered = String(decoding: bytes, as: UTF8.self)
        #expect(throws: AppError.self) {
            _ = try SecretBox.decryptIfPresent(tampered, field: Self.field)
        }
    }

    @Test("malformed base64 payload throws")
    func malformed_base64_throws() {
        #expect(throws: AppError.self) {
            _ = try SecretBox.decryptIfPresent("enc:v1:not!valid!base64!!!", field: Self.field)
        }
    }

    @Test("empty plaintext round-trips correctly")
    func empty_plaintext() throws {
        let enc = try SecretBox.encrypt("", field: Self.field)
        #expect(try SecretBox.decryptIfPresent(enc, field: Self.field) == "")
    }

    @Test("unicode plaintext round-trips correctly")
    func unicode_plaintext() throws {
        let pt = "chave-muito-secreta-çÇ-ñÑ-üÜ-日本語"
        let enc = try SecretBox.encrypt(pt, field: Self.field)
        #expect(try SecretBox.decryptIfPresent(enc, field: Self.field) == pt)
    }

    @Test("long plaintext (8 KB) round-trips correctly")
    func long_plaintext() throws {
        let pt = String(repeating: "x", count: 8192)
        let enc = try SecretBox.encrypt(pt, field: Self.field)
        #expect(try SecretBox.decryptIfPresent(enc, field: Self.field) == pt)
    }
}
